portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/users/')),
    path('users/', include('users.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('api_compara_datas/', include('api_compara_datas.urls')),
    path('api_geolocation/', include('api_geolocation.urls')),
    path('api_informa_dia_util/', include('api_informa_dia_util.urls')),
    path('api_replace_text/', include('api_replace_text.urls')),
    path('api_cpf_cnpj/', include('api_cpf_cnpj.urls')),
    path('api_telefone_latam/', include('api_telefone_latam.urls')),
]

register/urls.py
from django.urls import path

from . import views


app_name = 'register'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('validate_email/', views.validate_email, name='validate_email'),
    path('change_password/', views.change_password, name='change_password'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns =[
    path('', views.index, name='index'),
    path('lang/en/', views.index_en, name='index_en'),
    path('login/', views.login, name='login'),
]

register/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from users.models import CustomUser
from django.utils.translation import gettext_lazy as _

def new(request):

    if request.method == 'GET':

        return render(request, 'register/new.html')

    elif request.method == 'POST':

        post_data = request.POST
        forms_email = post_data.get('email')
        forms_password = post_data.get('password')
        forms_passwordconfirm = post_data.get('passwordconfirm')

        if CustomUser.objects.filter(email=forms_email).exists():
            email_errors = {
                'unique_email': _('Este e-mail já está sendo utilizado!')
            }
            return render(request, 'register/new.html', {'email_errors': email_errors})

        elif forms_password != forms_passwordconfirm:
            password_errors = {
                'unequal_password': _('As senhas não conferem!')
            }
            return render(request, 'register/new.html', {'password_errors': password_errors})

        else:
            u = CustomUser(
                email=post_data.get('email'),
                password=post_data.get('password'),
                first_name=post_data.get('name'),
                last_name=post_data.get('lastname')
            )
            u.set_password(post_data.get("password"))
            u.save()

            return render(request, 'register/success.html')

    return render(request, 'register/success.html')

def validate_email(request):

    if request.method == 'GET':

        return render(request, 'change_password/validate_email.html')

    elif request.method == 'POST':

        post_data_validate_email = request.POST
        forms_email_validate_email = post_data_validate_email.get('validateemail')

        if CustomUser.objects.filter(email=forms_email_validate_email).exists():

            user = get_object_or_404(CustomUser, email=forms_email_validate_email)
            request.session['user_token'] = str(user.token)

            return redirect(reverse('register:change_password'))

        else:

            unknown_email = {
                'unknown_email': _('Este e-mail não existe em nossa base de dados!')
            }
            return render(request, 'change_password/validate_email.html', {'unknown_email': unknown_email})

def change_password(request):
    user_token = request.session.get('user_token')
    user = get_object_or_404(CustomUser, token=user_token)

    if request.method == 'GET':

        return render(request, 'change_password/change_password.html')

    elif request.method == 'POST':

        password = request.POST.get('changepassword')
        new_password = request.POST.get('changepasswordconfirm')

        if password != new_password:
            password_errors = {
                'unequal_password': _('As senhas não conferem!')
            }
            return render(request, 'change_password/change_password.html', {'password_errors': password_errors})

        else:

            user.set_password(new_password)
            user.save()

            del request.session['user_token']

            return render(request, 'change_password/success_change_password.html')

register/templates/change_password/change_password.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1" style="background-color: #2FACAE; padding: 20px; border-radius: 10px">
    <div class="row mb-3">
        <div class="logo-container">
            <img
                    src="{% static 'logo.png' %}"
                    alt="Hi Platform"
                    width="150"
            >
        </div>
    </div>
    {% if user.is_authenticated %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-1 align-self-center text-center">
                <h4>Atenção!</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h4>Você <strong>já está logado!</strong></h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <p>Para retornar ao início: <a href="{% url 'users:index' %}">Clique aqui!</a></p>
            </div>
        </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h5>Digite sua nova senha:</h5>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2">
                <form action="" method="POST">
                    {% csrf_token %}
                        <div class="mb-2">
                            <label for="inputChangePassword" class="form-label fw-medium text-white">Senha</label>
                            <input
                                    type="password"
                                    name="changepassword"
                                    class="form-control rounded-3"
                                    id="inputChangePassword"
                                    placeholder="Informe sua nova senha"
                                    required
                            >
                        </div>
                        <div class="mb-2">
                            <label for="inputChangePasswordConfirm" class="form-label fw-medium text-white">Confirmar Senha</label>
                            <input
                                    type="password"
                                    name="changepasswordconfirm"
                                    class="form-control rounded-3"
                                    id="inputChangePasswordConfirm"
                                    placeholder="Confirme sua nova senha"
                                    required
                            >
                        </div>
                        <div class="row justify-content-center">
                            <div class="row md-6 mb-4 justify-content-center">
                                <button type="submit" class="btn btn-secondary" style="width: 350px">Cadastrar</button>
                            </div>
                        </div>
                </form>
                <div class="row justify-content-center">
                    <div class="col md-6 mb-0 align-self-center text-center">
                        <a href="{% url 'users:login' %}">Início</a>
                    </div>
                </div>
                {% if password_errors %}
                    <script>
                        alert("{{ password_errors.unequal_password }}");
                    </script>
                {% endif %}
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}

register/templates/change_password/success_change_password.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1" style="background-color: #2FACAE; padding: 20px; border-radius: 10px">
    <div class="row mb-3">
        <div class="logo-container">
            <img
                    src="{% static 'logo.png' %}"
                    alt="Hi Platform"
                    width="150"
            >
        </div>
    </div>
    {% if user.is_authenticated %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-1 align-self-center text-center">
                <h4>Atenção!</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h4>Você <strong>já está logado!</strong></h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <p>Para retornar ao início: <a href="{% url 'users:index' %}">Clique aqui!</a></p>
            </div>
        </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2">
                <div class="row justify-content-center">
                    <div class="col md-6 mb-0 align-self-center text-center">
                        <h4>Senha alterada com sucesso!</h4>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col md-6 mb-0 align-self-center text-center">
                        <p class="fw-medium mt-3">Clique no botão abaixo para iniciar:</p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col md-6 mb-0 align-self-center text-center">
                        <a href="{% url 'users:login' %}" class="btn btn-secondary">Login</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}

register/templates/change_password/validate_email.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container mt-1 mb-1" style="background-color: #2FACAE; padding: 20px; border-radius: 10px">
    <div class="row mb-3">
        <div class="logo-container">
            <img
                    src="{% static 'logo.png' %}"
                    alt="Hi Platform"
                    width="150"
            >
        </div>
    </div>
    {% if user.is_authenticated %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-1 align-self-center text-center">
                <h4>Atenção!</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h4>Você <strong>já está logado!</strong></h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <p>Para retornar ao início: <a href="{% url 'users:index' %}">Clique aqui!</a></p>
            </div>
        </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h4>Redefinição de senha</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2 align-self-center text-center">
                <h5>Digite o e-mail da sua conta:</h5>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5 mb-2">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="inputValidateEmail" class="form-label fw-medium text-white">E-mail</label>
                        <input
                                type="email"
                                name="validateemail"
                                class="form-control rounded-3"
                                id="inputValidateEmail"
                                placeholder="Informe seu e-mail"
                                required
                        >
                    </div>
                    <div class="row justify-content-center">
                        <div class="row md-6 mb-4 justify-content-center">
                            <button type="submit" class="btn btn-secondary text-white" style="width: 350px">Confirmar</button>
                        </div>
                    </div>
                </form>
                <div class="row justify-content-center">
                    <div class="col md-6 mb-0 align-self-center text-center">
                        <a href="{% url 'users:login' %}">Início</a>
                    </div>
                </div>
                {% if unknown_email %}
                    <script>
                        alert("{{ unknown_email.unknown_email }}");
                    </script>
                {% endif %}
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}