portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/users/')),
    path('users/', include('users.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('api_compara_datas/', include('api_compara_datas.urls')),
    path('api_geolocation/', include('api_geolocation.urls')),
    path('api_informa_dia_util/', include('api_informa_dia_util.urls')),
    path('api_replace_text/', include('api_replace_text.urls')),
    path('api_cpf_cnpj/', include('api_cpf_cnpj.urls')),
    path('api_telefone_latam/', include('api_telefone_latam.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns =[
    path('', views.index, name='index'),
    path('lang/en/', views.index_en, name='index_en'),
    path('login/', views.login, name='login'),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = None
    email = models.EmailField(_("email address"), unique=True, null=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class CustomAuthenticationForm(forms.Form):
    username = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control rounded-3'}),
        label=_("E-mail"),
        error_messages={'required': 'Informe o seu e-mail.'}
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control rounded-3'}),
        label=_("Senha"),
        strip=False,
        error_messages={'required': 'Informe a sua senha.'},
    )

users/views.py
from django.shortcuts import render
from users.forms import CustomAuthenticationForm
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from django.contrib import messages

def login(request):

    form = CustomAuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})

def index(request):

    if request.method == 'GET':

        return render(request, 'inicio/index.html')

    elif request.method == 'POST':

        nome_completo = request.POST['name']
        email = request.POST['email']
        telefone = request.POST['telefone']

        subject = 'Formulário do Portfolio'
        body = f'Nome completo: {nome_completo}\nE-mail: {email}\nTelefone: {telefone}'

        smtp_server = 'smtp.gmail.com'
        smtp_port = 587
        smtp_username = 'lucasreinert96@gmail.com'
        smtp_password = 'odzf tcau fcso jsol'

        # Configuração do servidor SMTP
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_username, smtp_password)

        # Criação do e-mail
        msg = MIMEMultipart()
        msg['From'] = smtp_username
        msg['To'] = 'lucasreinert96@gmail.com'
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))

        server.sendmail(smtp_username, 'lucasreinert96@gmail.com', msg.as_string())

        server.quit()

        messages.success(request, 'E-mail enviado com sucesso!')
        return render(request, 'redirect/redirect_index.html')

    return render(request, 'inicio/index.html')

def index_en(request):

    if request.method == 'GET':

        return render(request, 'inicio/index_en.html')

    elif request.method == 'POST':

        nome_completo = request.POST['name']
        email = request.POST['email']
        telefone = request.POST['telefone']

        subject = 'Formulário do Portfolio'
        body = f'Nome completo: {nome_completo}\nE-mail: {email}\nTelefone: {telefone}'

        smtp_server = 'smtp.gmail.com'
        smtp_port = 587
        smtp_username = 'lucasreinert96@gmail.com'
        smtp_password = 'odzf tcau fcso jsol'

        # Configuração do servidor SMTP
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_username, smtp_password)

        # Criação do e-mail
        msg = MIMEMultipart()
        msg['From'] = smtp_username
        msg['To'] = 'lucasreinert96@gmail.com'
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))

        server.sendmail(smtp_username, 'lucasreinert96@gmail.com', msg.as_string())

        server.quit()

        messages.success(request, 'E-mail enviado com sucesso!')
        return render(request, 'redirect/redirect_index_en.html')

    return render(request, 'inicio/index_en.html')

users/templates/redirect/redirect_index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container rounded" style="width: 60%; background: linear-gradient(to bottom, #00ffff 0%, #660033 100%); padding-bottom: 20px">
  <div class="row justify-content-center">
      <div class="col-md-5 mb-1 align-self-center text-center">
          <h4>Mensagem enviada com sucesso!</h4>
      </div>
  </div>
  <div class="row justify-content-center">
      <div class="col-md-5 mb-2 align-self-center text-center">
          <p>Clique aqui para retornar ao início: <a href="{% url 'users:index' %}">Início</a></p>
      </div>
  </div>
</div>
{% endblock %}

users/templates/redirect/redirect_index_en.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container rounded" style="width: 60%; background: linear-gradient(to bottom, #00ffff 0%, #660033 100%); padding-bottom: 20px">
  <div class="row justify-content-center">
      <div class="col-md-5 mb-1 align-self-center text-center">
          <h4>Message sent successfully!</h4>
      </div>
  </div>
  <div class="row justify-content-center">
      <div class="col-md-5 mb-2 align-self-center text-center">
          <p>Click here to return to the index: <a href="{% url 'users:index_en' %}">Index</a></p>
      </div>
  </div>
</div>
{% endblock %}